// Code generated by protoc-gen-go. DO NOT EDIT.
// source: announcement.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// message 对应生成代码的 struct
// 定义客户端请求的数据格式
type GetAnnouncementListRequest struct {
	// [修饰符] 类型 字段名 = 标识符;
	ExchangeId           int32    `protobuf:"varint,1,opt,name=exchange_id,json=exchangeId,proto3" json:"exchange_id,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	LastTime             int64    `protobuf:"varint,3,opt,name=last_time,json=lastTime,proto3" json:"last_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAnnouncementListRequest) Reset()         { *m = GetAnnouncementListRequest{} }
func (m *GetAnnouncementListRequest) String() string { return proto.CompactTextString(m) }
func (*GetAnnouncementListRequest) ProtoMessage()    {}
func (*GetAnnouncementListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_announcement_b7a8e572d20ab62e, []int{0}
}
func (m *GetAnnouncementListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAnnouncementListRequest.Unmarshal(m, b)
}
func (m *GetAnnouncementListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAnnouncementListRequest.Marshal(b, m, deterministic)
}
func (dst *GetAnnouncementListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAnnouncementListRequest.Merge(dst, src)
}
func (m *GetAnnouncementListRequest) XXX_Size() int {
	return xxx_messageInfo_GetAnnouncementListRequest.Size(m)
}
func (m *GetAnnouncementListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAnnouncementListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAnnouncementListRequest proto.InternalMessageInfo

func (m *GetAnnouncementListRequest) GetExchangeId() int32 {
	if m != nil {
		return m.ExchangeId
	}
	return 0
}

func (m *GetAnnouncementListRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetAnnouncementListRequest) GetLastTime() int64 {
	if m != nil {
		return m.LastTime
	}
	return 0
}

type AnnouncementResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Link                 string   `protobuf:"bytes,3,opt,name=link,proto3" json:"link,omitempty"`
	Logo                 string   `protobuf:"bytes,4,opt,name=logo,proto3" json:"logo,omitempty"`
	PostedAt             int64    `protobuf:"varint,5,opt,name=posted_at,json=postedAt,proto3" json:"posted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnnouncementResponse) Reset()         { *m = AnnouncementResponse{} }
func (m *AnnouncementResponse) String() string { return proto.CompactTextString(m) }
func (*AnnouncementResponse) ProtoMessage()    {}
func (*AnnouncementResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_announcement_b7a8e572d20ab62e, []int{1}
}
func (m *AnnouncementResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnnouncementResponse.Unmarshal(m, b)
}
func (m *AnnouncementResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnnouncementResponse.Marshal(b, m, deterministic)
}
func (dst *AnnouncementResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnnouncementResponse.Merge(dst, src)
}
func (m *AnnouncementResponse) XXX_Size() int {
	return xxx_messageInfo_AnnouncementResponse.Size(m)
}
func (m *AnnouncementResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AnnouncementResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AnnouncementResponse proto.InternalMessageInfo

func (m *AnnouncementResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AnnouncementResponse) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *AnnouncementResponse) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

func (m *AnnouncementResponse) GetLogo() string {
	if m != nil {
		return m.Logo
	}
	return ""
}

func (m *AnnouncementResponse) GetPostedAt() int64 {
	if m != nil {
		return m.PostedAt
	}
	return 0
}

type GetAnnouncementListResponse struct {
	ErrorCode            int32                   `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage         string                  `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Data                 []*AnnouncementResponse `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *GetAnnouncementListResponse) Reset()         { *m = GetAnnouncementListResponse{} }
func (m *GetAnnouncementListResponse) String() string { return proto.CompactTextString(m) }
func (*GetAnnouncementListResponse) ProtoMessage()    {}
func (*GetAnnouncementListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_announcement_b7a8e572d20ab62e, []int{2}
}
func (m *GetAnnouncementListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAnnouncementListResponse.Unmarshal(m, b)
}
func (m *GetAnnouncementListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAnnouncementListResponse.Marshal(b, m, deterministic)
}
func (dst *GetAnnouncementListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAnnouncementListResponse.Merge(dst, src)
}
func (m *GetAnnouncementListResponse) XXX_Size() int {
	return xxx_messageInfo_GetAnnouncementListResponse.Size(m)
}
func (m *GetAnnouncementListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAnnouncementListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAnnouncementListResponse proto.InternalMessageInfo

func (m *GetAnnouncementListResponse) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *GetAnnouncementListResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *GetAnnouncementListResponse) GetData() []*AnnouncementResponse {
	if m != nil {
		return m.Data
	}
	return nil
}

type CreateAnnouncementRequest struct {
	// [修饰符] 类型 字段名 = 标识符;
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Abstract             string   `protobuf:"bytes,3,opt,name=abstract,proto3" json:"abstract,omitempty"`
	Link                 string   `protobuf:"bytes,4,opt,name=link,proto3" json:"link,omitempty"`
	ExchangeId           int32    `protobuf:"varint,5,opt,name=exchange_id,json=exchangeId,proto3" json:"exchange_id,omitempty"`
	Logo                 string   `protobuf:"bytes,6,opt,name=logo,proto3" json:"logo,omitempty"`
	ExchangeName         string   `protobuf:"bytes,7,opt,name=exchange_name,json=exchangeName,proto3" json:"exchange_name,omitempty"`
	ExchangeAlias        string   `protobuf:"bytes,8,opt,name=exchange_alias,json=exchangeAlias,proto3" json:"exchange_alias,omitempty"`
	PostedAt             int64    `protobuf:"varint,9,opt,name=posted_at,json=postedAt,proto3" json:"posted_at,omitempty"`
	LangType             string   `protobuf:"bytes,10,opt,name=lang_type,json=langType,proto3" json:"lang_type,omitempty"`
	Source               string   `protobuf:"bytes,11,opt,name=source,proto3" json:"source,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAnnouncementRequest) Reset()         { *m = CreateAnnouncementRequest{} }
func (m *CreateAnnouncementRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAnnouncementRequest) ProtoMessage()    {}
func (*CreateAnnouncementRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_announcement_b7a8e572d20ab62e, []int{3}
}
func (m *CreateAnnouncementRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAnnouncementRequest.Unmarshal(m, b)
}
func (m *CreateAnnouncementRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAnnouncementRequest.Marshal(b, m, deterministic)
}
func (dst *CreateAnnouncementRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAnnouncementRequest.Merge(dst, src)
}
func (m *CreateAnnouncementRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAnnouncementRequest.Size(m)
}
func (m *CreateAnnouncementRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAnnouncementRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAnnouncementRequest proto.InternalMessageInfo

func (m *CreateAnnouncementRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CreateAnnouncementRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CreateAnnouncementRequest) GetAbstract() string {
	if m != nil {
		return m.Abstract
	}
	return ""
}

func (m *CreateAnnouncementRequest) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

func (m *CreateAnnouncementRequest) GetExchangeId() int32 {
	if m != nil {
		return m.ExchangeId
	}
	return 0
}

func (m *CreateAnnouncementRequest) GetLogo() string {
	if m != nil {
		return m.Logo
	}
	return ""
}

func (m *CreateAnnouncementRequest) GetExchangeName() string {
	if m != nil {
		return m.ExchangeName
	}
	return ""
}

func (m *CreateAnnouncementRequest) GetExchangeAlias() string {
	if m != nil {
		return m.ExchangeAlias
	}
	return ""
}

func (m *CreateAnnouncementRequest) GetPostedAt() int64 {
	if m != nil {
		return m.PostedAt
	}
	return 0
}

func (m *CreateAnnouncementRequest) GetLangType() string {
	if m != nil {
		return m.LangType
	}
	return ""
}

func (m *CreateAnnouncementRequest) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

// 定义服务端响应的数据格
type CreateAnnouncementResponse struct {
	ErrorCode            int32    `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAnnouncementResponse) Reset()         { *m = CreateAnnouncementResponse{} }
func (m *CreateAnnouncementResponse) String() string { return proto.CompactTextString(m) }
func (*CreateAnnouncementResponse) ProtoMessage()    {}
func (*CreateAnnouncementResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_announcement_b7a8e572d20ab62e, []int{4}
}
func (m *CreateAnnouncementResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAnnouncementResponse.Unmarshal(m, b)
}
func (m *CreateAnnouncementResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAnnouncementResponse.Marshal(b, m, deterministic)
}
func (dst *CreateAnnouncementResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAnnouncementResponse.Merge(dst, src)
}
func (m *CreateAnnouncementResponse) XXX_Size() int {
	return xxx_messageInfo_CreateAnnouncementResponse.Size(m)
}
func (m *CreateAnnouncementResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAnnouncementResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAnnouncementResponse proto.InternalMessageInfo

func (m *CreateAnnouncementResponse) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *CreateAnnouncementResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func init() {
	proto.RegisterType((*GetAnnouncementListRequest)(nil), "pb.GetAnnouncementListRequest")
	proto.RegisterType((*AnnouncementResponse)(nil), "pb.AnnouncementResponse")
	proto.RegisterType((*GetAnnouncementListResponse)(nil), "pb.GetAnnouncementListResponse")
	proto.RegisterType((*CreateAnnouncementRequest)(nil), "pb.CreateAnnouncementRequest")
	proto.RegisterType((*CreateAnnouncementResponse)(nil), "pb.CreateAnnouncementResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AnnouncementServiceClient is the client API for AnnouncementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AnnouncementServiceClient interface {
	GetAnnouncementList(ctx context.Context, in *GetAnnouncementListRequest, opts ...grpc.CallOption) (*GetAnnouncementListResponse, error)
	CreateAnnouncement(ctx context.Context, in *CreateAnnouncementRequest, opts ...grpc.CallOption) (*CreateAnnouncementResponse, error)
}

type announcementServiceClient struct {
	cc *grpc.ClientConn
}

func NewAnnouncementServiceClient(cc *grpc.ClientConn) AnnouncementServiceClient {
	return &announcementServiceClient{cc}
}

func (c *announcementServiceClient) GetAnnouncementList(ctx context.Context, in *GetAnnouncementListRequest, opts ...grpc.CallOption) (*GetAnnouncementListResponse, error) {
	out := new(GetAnnouncementListResponse)
	err := c.cc.Invoke(ctx, "/pb.AnnouncementService/GetAnnouncementList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *announcementServiceClient) CreateAnnouncement(ctx context.Context, in *CreateAnnouncementRequest, opts ...grpc.CallOption) (*CreateAnnouncementResponse, error) {
	out := new(CreateAnnouncementResponse)
	err := c.cc.Invoke(ctx, "/pb.AnnouncementService/CreateAnnouncement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnnouncementServiceServer is the server API for AnnouncementService service.
type AnnouncementServiceServer interface {
	GetAnnouncementList(context.Context, *GetAnnouncementListRequest) (*GetAnnouncementListResponse, error)
	CreateAnnouncement(context.Context, *CreateAnnouncementRequest) (*CreateAnnouncementResponse, error)
}

func RegisterAnnouncementServiceServer(s *grpc.Server, srv AnnouncementServiceServer) {
	s.RegisterService(&_AnnouncementService_serviceDesc, srv)
}

func _AnnouncementService_GetAnnouncementList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAnnouncementListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnnouncementServiceServer).GetAnnouncementList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AnnouncementService/GetAnnouncementList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnnouncementServiceServer).GetAnnouncementList(ctx, req.(*GetAnnouncementListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnnouncementService_CreateAnnouncement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAnnouncementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnnouncementServiceServer).CreateAnnouncement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AnnouncementService/CreateAnnouncement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnnouncementServiceServer).CreateAnnouncement(ctx, req.(*CreateAnnouncementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AnnouncementService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.AnnouncementService",
	HandlerType: (*AnnouncementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAnnouncementList",
			Handler:    _AnnouncementService_GetAnnouncementList_Handler,
		},
		{
			MethodName: "CreateAnnouncement",
			Handler:    _AnnouncementService_CreateAnnouncement_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "announcement.proto",
}

func init() { proto.RegisterFile("announcement.proto", fileDescriptor_announcement_b7a8e572d20ab62e) }

var fileDescriptor_announcement_b7a8e572d20ab62e = []byte{
	// 457 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xce, 0x0f, 0xf1, 0x04, 0x7a, 0xd8, 0x56, 0x68, 0x71, 0xd5, 0x36, 0x32, 0x42, 0xca,
	0x01, 0xe5, 0x50, 0x9e, 0x20, 0xea, 0x01, 0x21, 0x01, 0x07, 0x53, 0x24, 0x6e, 0x66, 0x63, 0x8f,
	0xcc, 0x0a, 0x7b, 0xd7, 0x78, 0x27, 0x88, 0x1e, 0x79, 0x02, 0x5e, 0x0a, 0xf1, 0x5c, 0xc8, 0xbb,
	0xb6, 0xe5, 0xd0, 0x58, 0xe2, 0xc0, 0x2d, 0xf3, 0xcd, 0xec, 0xec, 0xf7, 0xb3, 0x31, 0x30, 0xa1,
	0x94, 0xde, 0xab, 0x14, 0x4b, 0x54, 0xb4, 0xa9, 0x6a, 0x4d, 0x9a, 0xf9, 0xd5, 0x2e, 0xaa, 0x20,
	0x7c, 0x85, 0xb4, 0x1d, 0x34, 0xdf, 0x48, 0x43, 0x31, 0x7e, 0xdd, 0xa3, 0x21, 0x76, 0x05, 0x4b,
	0xfc, 0x9e, 0x7e, 0x16, 0x2a, 0xc7, 0x44, 0x66, 0xdc, 0x5b, 0x79, 0xeb, 0x59, 0x0c, 0x1d, 0xf4,
	0x3a, 0x63, 0x67, 0x30, 0x2b, 0x64, 0x29, 0x89, 0xfb, 0xb6, 0xe5, 0x0a, 0x76, 0x0e, 0x41, 0x21,
	0x0c, 0x25, 0x24, 0x4b, 0xe4, 0x93, 0x95, 0xb7, 0x9e, 0xc4, 0x8b, 0x06, 0xb8, 0x95, 0x25, 0x46,
	0x3f, 0x3c, 0x38, 0x1b, 0xde, 0x17, 0xa3, 0xa9, 0xb4, 0x32, 0xc8, 0x4e, 0xc0, 0xef, 0xef, 0xf0,
	0xa5, 0xdd, 0x4d, 0x92, 0x0a, 0xb4, 0xbb, 0x83, 0xd8, 0x15, 0x8c, 0xc1, 0xb4, 0x90, 0xea, 0x8b,
	0x5d, 0x1b, 0xc4, 0xf6, 0xb7, 0xc5, 0x74, 0xae, 0xf9, 0xb4, 0xc5, 0x74, 0xae, 0x1b, 0x0e, 0x95,
	0x36, 0x84, 0x59, 0x22, 0x88, 0xcf, 0x1c, 0x07, 0x07, 0x6c, 0x29, 0xfa, 0xe9, 0xc1, 0xf9, 0x51,
	0xd9, 0x2d, 0x95, 0x0b, 0x00, 0xac, 0x6b, 0x5d, 0x27, 0xa9, 0xce, 0xb0, 0xa5, 0x14, 0x58, 0xe4,
	0x46, 0x67, 0xc8, 0x9e, 0xc1, 0x63, 0xd7, 0x2e, 0xd1, 0x18, 0x91, 0x77, 0x0c, 0x1f, 0x59, 0xf0,
	0xad, 0xc3, 0xd8, 0x0b, 0x98, 0x66, 0x82, 0x04, 0x9f, 0xac, 0x26, 0xeb, 0xe5, 0x35, 0xdf, 0x54,
	0xbb, 0xcd, 0x31, 0xd9, 0xb1, 0x9d, 0x8a, 0x7e, 0xf9, 0xf0, 0xf4, 0xa6, 0x46, 0x41, 0x78, 0x38,
	0xe4, 0x72, 0xf8, 0x37, 0x6b, 0x42, 0x58, 0x88, 0x9d, 0xa1, 0x5a, 0xa4, 0xd4, 0xda, 0xd3, 0xd7,
	0xbd, 0x6d, 0xd3, 0x81, 0x6d, 0x7f, 0xa5, 0x3b, 0xbb, 0x97, 0x6e, 0xe7, 0xeb, 0x7c, 0xe0, 0x6b,
	0xa3, 0xbd, 0x3b, 0xa4, 0x44, 0x89, 0xfc, 0x61, 0xab, 0xbd, 0x05, 0xdf, 0x89, 0x12, 0xd9, 0x73,
	0x38, 0xe9, 0x87, 0x44, 0x21, 0x85, 0xe1, 0x0b, 0x3b, 0xd5, 0x1f, 0xdd, 0x36, 0xe0, 0x61, 0x46,
	0xc1, 0x61, 0x46, 0xee, 0x11, 0xa9, 0x3c, 0xa1, 0xbb, 0x0a, 0x39, 0x38, 0x39, 0x0d, 0x70, 0x7b,
	0x57, 0x21, 0x7b, 0x02, 0x73, 0xa3, 0xf7, 0x75, 0x8a, 0x7c, 0x69, 0x3b, 0x6d, 0x15, 0x7d, 0x82,
	0xf0, 0x98, 0x8b, 0xff, 0x2f, 0xd6, 0xeb, 0xdf, 0x1e, 0x9c, 0x0e, 0x97, 0xbf, 0xc7, 0xfa, 0x9b,
	0x4c, 0x91, 0x7d, 0x84, 0xd3, 0x23, 0x2f, 0x8a, 0x5d, 0x36, 0xb9, 0x8f, 0xff, 0xc3, 0xc2, 0xab,
	0xd1, 0xbe, 0xe3, 0x1c, 0x3d, 0x60, 0x1f, 0x80, 0xdd, 0xd7, 0xc4, 0x2e, 0x9a, 0x83, 0xa3, 0x2f,
	0x26, 0xbc, 0x1c, 0x6b, 0x77, 0x6b, 0x77, 0x73, 0xfb, 0x11, 0x78, 0xf9, 0x27, 0x00, 0x00, 0xff,
	0xff, 0x9d, 0x2c, 0xc8, 0xa1, 0x1a, 0x04, 0x00, 0x00,
}
